#!/bin/bash

# Script: sudo-hardening-pro_tweaks
# Author: [NAZY-OS]
# Description: [Shows various of system errors and warnings]


for netdev in $(cat /proc/net/dev | grep : | awk -F ":" '{ print $1 }' | grep -v lo)  
do
  echo Change MAC of device: $netdev
  echo
  sudo ip link set dev $netdev down
  sleep 0.2
  sudo macchanger -r $netdev
  sleep 0.2
  sudo ip link set dev $netdev up
  echo
done
